#include <stdlib.h>
#include "my_malloc.h"
#include "list.h"

int main() {
    int i = 111;
	LIST* list = create_list();
	pushFront(list, 3);
	pushFront(list, 2);
	pushFront(list, 1);
	pushFront(list, 3);
	pushFront(list, 2);
	pushFront(list, 1);
	pushFront(list, 3);
	pushFront(list, 2);
	pushFront(list, 1);
	pushFront(list, 3);
	pushFront(list, 2);
	pushFront(list, 1);
	pushFront(list, 3);
	pushFront(list, 2);
	pushFront(list, 1);
	pushFront(list, 3);
	pushFront(list, 2);
	pushFront(list, 1);
	pushFront(list, 3);
	pushFront(list, 2);
	pushFront(list, 1);
	pushFront(list, 3);
	pushFront(list, 2);
	pushFront(list, 1);
	pushFront(list, 3);
	pushFront(list, 2);
	pushFront(list, 1);
	pushFront(list, 3);
	pushFront(list, 2);
	pushFront(list, 1);
	pushFront(list, 3);
	pushFront(list, 2);
	pushFront(list, 1);
	pushFront(list, 3);
	pushFront(list, 2);
	pushFront(list, 1);
	pushFront(list, 3);
	pushFront(list, 2);
	pushFront(list, 1);
	pushFront(list, 3);
	pushFront(list, 2);
	pushFront(list, 1);
	pushFront(list, 3);
	pushFront(list, 2);
	pushFront(list, 1);
	pushFront(list, 3);
	pushFront(list, 2);
	pushFront(list, 1);
	pushFront(list, 3);
	pushFront(list, 2);
	pushFront(list, 1);
	pushFront(list, 3);
	pushFront(list, 2);
	pushFront(list, 1);
	pushFront(list, 3);
	pushFront(list, 2);
	pushFront(list, 1);
	pushFront(list, 3);
	pushFront(list, 2);
	pushFront(list, 1);
	pushFront(list, 3);
	pushFront(list, 2);
	pushFront(list, 1);
	pushFront(list, 3);
	pushFront(list, 2);
	pushFront(list, 1);
	pushFront(list, 3);
	pushFront(list, 2);
	pushFront(list, 1);
	pushFront(list, 3);
	pushFront(list, 2);
	pushFront(list, 1);
	pushFront(list, 3);
	pushFront(list, 2);
	pushFront(list, 1);
	pushFront(list, 3);
	pushFront(list, 2);
	pushFront(list, 1);
	pushFront(list, 3);
	pushFront(list, 2);
	pushFront(list, 1);
	pushFront(list, 3);
	pushFront(list, 2);
	pushFront(list, 1);
	pushFront(list, 3);
	pushFront(list, 2);
	pushFront(list, 1);
	pushFront(list, 3);
	pushFront(list, 2);
	pushFront(list, 1);
	pushFront(list, 3);
	pushFront(list, 2);
	pushFront(list, 1);
	pushFront(list, 3);
	pushFront(list, 2);
	pushFront(list, 1);
	pushFront(list, 3);
	pushFront(list, 2);
	pushFront(list, 1);
	pushFront(list, 3);
	pushFront(list, 2);
	pushFront(list, 1);
	pushFront(list, 3);
	pushFront(list, 2);
	pushFront(list, 1);
	pushFront(list, 3);
	pushFront(list, 2);
	pushFront(list, 1);
	pushFront(list, 3);
	pushFront(list, 2);
	pushFront(list, 1);
	pushFront(list, 3);
	pushFront(list, 2);
	pushFront(list, 1);
	pushFront(list, 3);
	pushFront(list, 2);
	pushFront(list, 1);
	pushFront(list, 3);
	pushFront(list, 2);
	pushFront(list, 1);
	pushFront(list, 3);
	pushFront(list, 2);
	pushFront(list, 1);
	pushFront(list, 3);
	pushFront(list, 2);
	pushFront(list, 1);
	pushFront(list, 3);
	pushFront(list, 2);
	pushFront(list, 1);
	pushFront(list, 3);
	pushFront(list, 2);
	pushFront(list, 1);
	pushFront(list, 3);
	pushFront(list, 2);
	pushFront(list, 1);
	pushFront(list, 3);
	pushFront(list, 2);
	pushFront(list, 1);
	pushFront(list, 3);
	pushFront(list, 2);
	pushFront(list, 1);
	pushFront(list, 3);
	pushFront(list, 2);
	pushFront(list, 1);
	pushFront(list, 3);
	pushFront(list, 2);
	pushFront(list, 1);
	pushFront(list, 3);
	pushFront(list, 2);
	pushFront(list, 1);
	pushFront(list, 3);
	pushFront(list, 2);
	pushFront(list, 1);
	pushFront(list, 3);
	pushFront(list, 2);
	pushFront(list, 1);
	pushFront(list, 3);
	pushFront(list, 2);
	pushFront(list, 1);
	pushFront(list, 3);
	pushFront(list, 2);
	pushFront(list, 1);
	pushFront(list, 3);
	pushFront(list, 2);
	pushFront(list, 1);
	pushFront(list, 3);
	pushFront(list, 2);
	pushFront(list, 1);
	pushFront(list, 3);
	pushFront(list, 2);
	pushFront(list, 1);
	pushFront(list, 3);
	pushFront(list, 2);
	pushFront(list, 1);
	pushFront(list, 3);
	pushFront(list, 2);
	pushFront(list, 1);
	pushFront(list, 3);
	pushFront(list, 2);
	pushFront(list, 1);
	pushFront(list, 3);
	pushFront(list, 2);
	pushFront(list, 1);
	pushFront(list, 3);
	pushFront(list, 2);
	pushFront(list, 1);
	pushFront(list, 3);
	pushFront(list, 2);
	pushFront(list, 1);
	pushFront(list, 3);
	pushFront(list, 2);
	pushFront(list, 1);
	popBack(list);
	popBack(list);
	popFront(list);
	popBack(list);
	popBack(list);
	popFront(list);
	popBack(list);
	popBack(list);
	popFront(list);
	popBack(list);
	popBack(list);
	popFront(list);
	popBack(list);
	popBack(list);
	popFront(list);
	popBack(list);
	popBack(list);
	popFront(list);
	popBack(list);
	popBack(list);
	popFront(list);
	popBack(list);
	popBack(list);
	popFront(list);
	popBack(list);
	popBack(list);
	popFront(list);
	popBack(list);
	popBack(list);
	popFront(list);
	popBack(list);
	popBack(list);
	popFront(list);
	popBack(list);
	popBack(list);
	popFront(list);
	popBack(list);
	popBack(list);
	popFront(list);
	popBack(list);
	popBack(list);
	popFront(list);
	popBack(list);
	popBack(list);
	popFront(list);
	popBack(list);
	popBack(list);
	popFront(list);
	popBack(list);
	popBack(list);
	popFront(list);
	popBack(list);
	popBack(list);
	popFront(list);
	popBack(list);
	popBack(list);
	popFront(list);
	popBack(list);
	popBack(list);
	popFront(list);
	popBack(list);
	popBack(list);
	popFront(list);
	popBack(list);
	popBack(list);
	popFront(list);
	popBack(list);
	popBack(list);
	popFront(list);
	popBack(list);
	popBack(list);
	popFront(list);
	popBack(list);
	popBack(list);
	popFront(list);
	popBack(list);
	popBack(list);
	popFront(list);
	popBack(list);
	popBack(list);
	popFront(list);
	popBack(list);
	popBack(list);
	popFront(list);
	popBack(list);
	popBack(list);
	popFront(list);
	popBack(list);
	popBack(list);
	popFront(list);
	popBack(list);
	popBack(list);
	popFront(list);
	popBack(list);
	popBack(list);
	popFront(list);
	popBack(list);
	popBack(list);
	popFront(list);
	popBack(list);
	popBack(list);
	popFront(list);
	popBack(list);
	popBack(list);
	popFront(list);
	popBack(list);
	popBack(list);
	popFront(list);
	popBack(list);
	popBack(list);
	popFront(list);
	popBack(list);
	popBack(list);
	popFront(list);
	popBack(list);
	popBack(list);
	popFront(list);
	popBack(list);
	popBack(list);
	popFront(list);
	popBack(list);
	popBack(list);
	popFront(list);
	popBack(list);
	popBack(list);
	popFront(list);
	popBack(list);
	popBack(list);
	popFront(list);
	popBack(list);
	popBack(list);
	popFront(list);
	i = popBack(list);
  	printf("I just popped %d.\n", i);
	checklist();
	// void* soso = my_malloc(2037);
	// void* soya = my_malloc(2036);
	// printf("He doesn't let me have soso! %d, and %d.\n", (int)soso, (int)soya);
	 
	return 0;
}
